### PR TITLE
Vencenty formula

### PR DESCRIPTION
**Pull request by eduha**
Vencenti formula for more accurate track distance calculation

### CODE REVIEW

**Comment by tmuguet** [comment]
Hi @eduha , thanks for your contribution!
I am curious though about use cases where the default formula is not accurate enough, do you have an example?

**Comment by eduha** [comment]
@tmuguet 

I'm a cyclist and ride brevets. We have 601 km planned tour next year, and I tried to import the GPX track (the file is attached) on map2gpx.eu - and it calculates distance as 599.4 km.

With Vencenty formula the distance is calculated as 600.65 km which is more close to 601.


[BRM 600 Hi & bye, Bayanaul (Petrovka).zip](https://github.com/tmuguet/map2gpx/files/5485550/BRM.600.Hi.bye.Bayanaul.Petrovka.zip)

**Comment by eduha** [comment]
@tmuguet 

Actually, the track distance measured with Google Earth is 600.649 km, so Vincenty formula is pretty accurate 


image

**Comment by eduha** [comment]
Sorry for several messages, here isanother example: 4 km difference on 1000km track 

[BRM 1000 Ekibastuz.zip](https://github.com/tmuguet/map2gpx/files/5485583/BRM.1000.Ekibastuz.zip)

**Comment by tmuguet** [comment]
Interesting, I never thought of having tracks that long, I'm even surprised map2gpx handles it quite well.
I'll merge your modifications and deploy them today. As a long-term solution, I'll integrate this formula in [Leaflet.TrackStats](https://github.com/tmuguet/Leaflet.TrackStats) instead.

Thanks for your contribution!

**Pull request merged**
